unsafeHttpWhitelist:
  - npm.decodeit.co

npmRegistries:
  "https://npm.decodeit.co":
    npmAlwaysAuth: true
    npmAuthToken: vxApQRq18XvCsT5L9uEkrowfk4N4SY/A51AjwppszaQ=

npmScopes:
  interzero:
    npmRegistryServer: "https://npm.decodeit.co"

  decodeit:
    npmRegistryServer: "https://npm.decodeit.co"
